language: node_js
node_js:
  - "7"
osx_image: xcode11.3

branches:
  only:
  - setup-travis-ci

env:
  global:
  - NODE_VERSION=stable

install: 
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
  - export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - nvm alias default $NODE_VERSION
  - npm install -g react-native-cli
  - npm install
  - npm i -g detox-cli
  - npm install detox
  # - sudo apt install linuxbrew-wrapper
  # - brew tap wix/brew
  # - brew install applesimutils
 

# script:
  - npm run dl_expo_bins
  # - npm run ios
  - npm run test:e2e
  
  # - yarn run lint
  # - yarn run detox:test:ios:release
  # - detox build --configuration ios.sim
  # - detox test --configuration ios.sim --cleanup