export const Auth = {
  SIGN_UP_ATTEMPT: 'SIGN_UP_ATTEMPT',
  ADD_SESSION: 'ADD_SESSION',
  SIGN_UP_FAIL: 'SIGN_UP_FAIL',
  CLEAR_REQUEST_ERROR: 'CLEAR_REQUEST_ERROR',
  START_A_REQUEST: 'START_A_REQUEST',
  UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_FAIL: 'UPDATE_PROFILE_FAIL'
};
