export const Auth = {
  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  VERIFY_ACCOUNT_START: 'VERIFY_ACCOUNT_START',
  VERIFY_ACCOUNT_SUCCESS: 'VERIFY_ACCOUNT_SUCCESS',
  VERIFY_ACCOUNT_FAILURE: 'VERIFY_ACCOUNT_FAILURE',

  RESET_PASSWORD_START: 'RESET_PASSWORD_START',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',

  RESEND_OTP_START: 'RESEND_OTP_START',
  RESEND_OTP_FAILURE: 'RESEND_OTP_FAILURE',
  RESEND_OTP_SUCCESS: 'RESEND_OTP_SUCCESS',

  RESET_PASSWORD_VERIFY_START: 'RESET_PASSWORD_VERIFY_START',
  RESET_PASSWORD_VERIFY_FAILURE: 'RESET_PASSWORD_VERIFY_FAILURE',
  RESET_PASSWORD_VERIFY_SUCCESS: 'RESET_PASSWORD_VERIFY_SUCCESS',

  SIGNUP_START: 'SIGNUP_START',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',

  ADD_SESSION: 'ADD_SESSION',
  SIGN_UP_FAIL: 'SIGN_UP_FAIL',
  CLEAR_REQUEST_ERROR: 'CLEAR_REQUEST_ERROR',
  DELETE_ACCOUNT_START: 'DELETE_ACCOUNT_START',
  DELETE_ACCOUNT_FAILURE: 'DELETE_ACCOUNT_FAILURE',
  DELETE_ACCOUNT_SUCCESS: 'DELETE_ACCOUNT_SUCCESS',

  LOGOUT: 'LOGOUT',
  GET_ACTIVE_STORIES_START: 'GET_ACTIVE_STORIES_START',
  GET_ACTIVE_STORIES_FAILURE: 'GET_ACTIVE_STORIES_FAILURE',
  GET_ACTIVE_STORIES_SUCCESS: 'GET_ACTIVE_STORIES_SUCCESS',
  UPDATE_ACTIVE_STORIES: 'UPDATE_ACTIVE_STORIES',
  GET_COMPLETED_STORIES_START: 'GET_ACTIVE_STORIES_START',
  GET_COMPLETED_STORIES_FAILURE: 'GET_ACTIVE_STORIES_FAILURE',
  GET_COMPLETED_STORIES_SUCCESS: 'GET_ACTIVE_STORIES_SUCCESS',
  GET_SELF_STORIES_START: 'GET_SELF_STORIES_START',
  GET_SELF_STORIES_FAILURE: 'GET_SELF_STORIES_FAILURE',
  GET_SELF_STORIES_COMPLETED: 'GET_SELF_STORIES_SUCCESS'
};

export const User = {
  UPDATE_PROFILE_START: 'UPDATE_PROFILE_START',
  UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_FAILURE: 'UPDATE_PROFILE_FAILURE',
  UPDATE_USER_PREFERENCE_START: 'UPDATE_USER_PREFERENCE_START',
  UPDATE_USER_PREFERENCE_SUCCESS: 'UPDATE_USER_PREFERENCE_SUCCESS',
  UPDATE_USER_PREFERENCE_FAILURE: 'UPDATE_USER_PREFERENCE_FAILURE'
};

export const Home = {
  SET_FILTERS: 'SET_FILTERS',
  GET_ACTIVE_STORIES_START: 'GET_ACTIVE_STORIES_START',
  GET_ACTIVE_STORIES_FAILURE: 'GET_ACTIVE_STORIES_FAILURE',
  GET_ACTIVE_STORIES_SUCCESS: 'GET_ACTIVE_STORIES_SUCCESS',
  UPDATE_ACTIVE_STORIES: 'UPDATE_ACTIVE_STORIES'
};
export const Library = {
  SET_FILTERS: 'SET_FILTERS',
  GET_COMPLETED_STORIES_START: 'GET_COMPLETED_STORIES_START',
  GET_COMPLETED_STORIES_FAILURE: 'GET_COMPLETED_STORIES_FAILURE',
  GET_COMPLETED_STORIES_SUCCESS: 'GET_COMPLETED_STORIES_SUCCESS'
};
export const Writing = {
  SET_FILTERS: 'SET_FILTERS',
  GET_SELF_STORIES_START: 'GET_SELF_STORIES_START',
  GET_SELF_STORIES_FAILURE: 'GET_SELF_STORIES_FAILURE',
  GET_SELF_STORIES_COMPLETED: 'GET_SELF_STORIES_SUCCESS'
};
