const LOGIN_START = 'LOGIN_START';
const LOGIN_SUCCESS = 'LOGIN_SUCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';
const ADD_SESSION = 'ADD_SESSION';
const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export { LOGIN_START, LOGIN_SUCCESS, LOGIN_FAILURE, ADD_SESSION, CLEAR_MESSAGE };
